export type Category = 'Starters' | 'Mains' | 'Wood-Fired' | 'Drinks' | 'Desserts'

export type HoursItem = {
  days: string
  time: string
  closed?: boolean
  indices: number[]
}

export const hoursData: HoursItem[] = [
  { days: 'Tuesday – Thursday', time: '5:00 PM – 10:00 PM', indices: [2, 3, 4] },
  { days: 'Friday – Saturday', time: '5:00 PM – 11:00 PM', indices: [5, 6] },
  { days: 'Sunday', time: '4:00 PM – 9:00 PM', indices: [0] },
  { days: 'Monday', time: 'Closed', closed: true, indices: [1] },
]

export const openDaysTag = 'Open Tue–Sun'

export type Dish = {
  id: string
  category: Category
  name: string
  description: string
  price: string
  veg: boolean
  chefsPick: boolean
  tag?: string
  note: string
  image: string
  ingredients: string[]
  allergens: string
  pairing: string
}

export const categories: Category[] = ['Starters', 'Mains', 'Wood-Fired', 'Drinks', 'Desserts']

export const dishes: Dish[] = [
  // Starters
  {
    id: 'starter-1',
    category: 'Starters',
    name: 'Tandoori Gobi',
    description: 'Charred cauliflower florets, mint chutney, chaat masala',
    price: '₹325',
    veg: true,
    chefsPick: false,
    note: 'Smoky florets, bright chutney, plenty of crunch.',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
    ingredients: ['Cauliflower', 'Mint Chutney', 'Yellow Mustard', 'Kashmiri Chilli', 'Chaat Masala'],
    allergens: 'Dairy (in marinade)',
    pairing: 'Smoked Tamarind Old Fashioned or Jeera Soda',
  },
  {
    id: 'starter-2',
    category: 'Starters',
    name: 'Amritsari Fish Tikka',
    description: 'River sole, ajwain, gram flour crust, tamarind chutney',
    price: '₹425',
    veg: false,
    chefsPick: true,
    note: 'A crisp Punjabi classic, straight from the sigri.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
    ingredients: ['River Sole', 'Ajwain (Carom Seeds)', 'Gram Flour (Besan)', 'Mustard Oil', 'Lemon Juice'],
    allergens: 'Fish, Mustard',
    pairing: 'Chilled Nimbu Pani or Crisp Lager',
  },
  {
    id: 'starter-3',
    category: 'Starters',
    name: 'Seekh Kebab',
    description: 'Minced lamb, char-grilled over sigri coals, ginger and green chilli',
    price: '₹450',
    veg: false,
    chefsPick: false,
    note: 'Hand-shaped and kissed by the sigri coals.',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=600&q=80',
    ingredients: ['Minced Lamb', 'Fresh Ginger', 'Green Chilli', 'Coriander Root', 'Garam Masala'],
    allergens: 'None',
    pairing: 'Smoked Tamarind Old Fashioned',
  },
  {
    id: 'starter-4',
    category: 'Starters',
    name: 'Papdi Chaat',
    description: 'Crisp flour wafers, spiced yogurt, tamarind chutney, crunchy sev',
    price: '₹295',
    veg: true,
    chefsPick: false,
    note: 'The table starter that never stays on the table.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
    ingredients: ['Flour Wafers (Papdi)', 'Spiced Yogurt', 'Tamarind Reduction', 'Fresh Mint', 'Gram Flour Sev'],
    allergens: 'Gluten, Dairy',
    pairing: 'Masala Chai or Nimbu Pani',
  },
  {
    id: 'starter-5',
    category: 'Starters',
    name: 'Smoky Paneer Tikka',
    description: 'Hand-pressed cottage cheese, charred bell peppers, smoked mustard oil',
    price: '₹395',
    veg: true,
    chefsPick: true,
    note: 'Golden blistered edges with a tender melted core.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=600&q=80',
    ingredients: ['Fresh Paneer', 'Bell Peppers', 'Red Onion', 'Hung Curd', 'Smoked Mustard Oil'],
    allergens: 'Dairy, Mustard',
    pairing: 'Jeera Soda',
  },

  // Mains
  {
    id: 'main-1',
    category: 'Mains',
    name: 'Butter Chicken',
    description: 'Char-grilled chicken in a rich tomato-cashew gravy with ember smoke',
    price: '₹625',
    veg: false,
    chefsPick: true,
    note: 'Our version is finished with a little ember smoke infusion.',
    image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=600&q=80',
    ingredients: ['Charred Chicken Thighs', 'San Marzano Tomatoes', 'Cashew Paste', 'White Butter', 'Kasuri Methi'],
    allergens: 'Dairy, Tree Nuts',
    pairing: 'Garlic Naan & Full-bodied Red Wine',
  },
  {
    id: 'main-2',
    category: 'Mains',
    name: 'Dal Makhani',
    description: '24-hour slow-simmered black lentils, smoked white butter, fenugreek',
    price: '₹475',
    veg: true,
    chefsPick: false,
    note: 'Low and slow, with a final gloss of charcoal-infused butter.',
    image: 'https://images.unsplash.com/photo-1546833998-877b37c2e5c6?auto=format&fit=crop&w=600&q=80',
    ingredients: ['Black Urad Dal', 'Rajma (Kidney Beans)', 'Tomato Puree', 'Cultured Butter', 'Dried Fenugreek'],
    allergens: 'Dairy',
    pairing: 'Tandoori Roti & Masala Chai',
  },
  {
    id: 'main-3',
    category: 'Mains',
    name: 'Rogan Josh',
    description: 'Kashmiri lamb curry slow-braised with fennel seed and dried ginger',
    price: '₹675',
    veg: false,
    chefsPick: false,
    note: 'Deeply spiced, never hurried, bone-in tenderness.',
    image: 'https://images.unsplash.com/photo-1545247181-516773cae754?auto=format&fit=crop&w=600&q=80',
    ingredients: ['Mutton Shank', 'Ratanjot (Alkanet Root)', 'Fennel Powder', 'Dry Ginger', 'Mustard Oil'],
    allergens: 'Mustard',
    pairing: 'Smoked Tamarind Old Fashioned',
  },
  {
    id: 'main-4',
    category: 'Mains',
    name: 'Paneer Lababdar',
    description: 'Charred paneer cubes in coarse tomato gravy, crushed kasuri methi',
    price: '₹525',
    veg: true,
    chefsPick: false,
    note: 'Soft paneer, blistered edges, rich rustic tomato.',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=600&q=80',
    ingredients: ['Fresh Paneer', 'Coarse Tomato Gravy', 'Onion', 'Ginger', 'Kasuri Methi', 'Fresh Cream'],
    allergens: 'Dairy',
    pairing: 'Butter Garlic Naan',
  },
  {
    id: 'main-5',
    category: 'Mains',
    name: 'Smoky Dum Biryani',
    description: 'Long-grain basmati rice and marinated lamb, seal-cooked over charcoal embers',
    price: '₹595',
    veg: false,
    chefsPick: true,
    note: 'Perfumed with saffron, kewra, and woodsmoke.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    ingredients: ['Basmati Rice', 'Marinated Mutton', 'Kashmiri Saffron', 'Caramelized Onion', 'Mint', 'Desi Ghee'],
    allergens: 'Dairy',
    pairing: 'Cucumber Burani Raita',
  },

  // Wood-Fired
  {
    id: 'wood-1',
    category: 'Wood-Fired',
    name: 'Tandoori Chicken',
    description: 'Whole leg marinated overnight in hung curd & spices, char-grilled',
    price: '₹595',
    veg: false,
    chefsPick: true,
    note: 'Marinated overnight, served with ring onions and lemon wedges.',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80',
    ingredients: ['Whole Chicken Leg', 'Hung Curd', 'Kashmiri Chilli', 'Ginger Garlic', 'Charcoal Smoke'],
    allergens: 'Dairy',
    pairing: 'Chilled Craft Beer',
  },
  {
    id: 'wood-2',
    category: 'Wood-Fired',
    name: 'Tandoori Prawns',
    description: 'Jumbo prawns, ajwain, roasted garlic, smoked chilli oil, lemon',
    price: '₹795',
    veg: false,
    chefsPick: false,
    note: 'Plump coastal prawns with a clean, smoky finish.',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80',
    ingredients: ['Jumbo Tiger Prawns', 'Ajwain', 'Garlic Butter', 'Smoked Red Chilli', 'Lemon Juice'],
    allergens: 'Crustaceans, Dairy',
    pairing: 'Dry White Wine or Nimbu Pani',
  },
  {
    id: 'wood-3',
    category: 'Wood-Fired',
    name: 'Malai Tikka',
    description: 'Charred chicken supreme marinated in cream, green cardamom, and white pepper',
    price: '₹625',
    veg: false,
    chefsPick: false,
    note: 'Silky, gentle heat, deeply tender texture.',
    image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=600&q=80',
    ingredients: ['Chicken Supreme', 'Heavy Cream', 'Green Cardamom', 'White Pepper', 'Processed Cheese'],
    allergens: 'Dairy',
    pairing: 'Jeera Soda or White Wine',
  },
  {
    id: 'wood-4',
    category: 'Wood-Fired',
    name: 'Tandoori Mushroom',
    description: 'Wild button mushrooms stuffed with spiced khoya, hung curd, black pepper',
    price: '₹475',
    veg: true,
    chefsPick: false,
    note: 'Earthy, smoky, and made for sharing across the table.',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=600&q=80',
    ingredients: ['Button Mushrooms', 'Spiced Khoya', 'Hung Curd', 'Black Pepper', 'Fresh Coriander'],
    allergens: 'Dairy',
    pairing: 'Masala Chai',
  },
  {
    id: 'wood-5',
    category: 'Wood-Fired',
    name: 'Charred Broccoli Malai',
    description: 'Broccoli crowns coated in cream cheese, mace, nutmeg, roasted in clay oven',
    price: '₹425',
    veg: true,
    chefsPick: true,
    note: 'Blistered florets with a rich, nutty crust.',
    image: 'https://images.unsplash.com/photo-1584270354949-c26b0d5b4a0c?auto=format&fit=crop&w=600&q=80',
    ingredients: ['Broccoli Crowns', 'Cream Cheese', 'Ground Nutmeg', 'Mace', 'Green Cardamom'],
    allergens: 'Dairy, Tree Nuts',
    pairing: 'Smoked Tamarind Old Fashioned',
  },

  // Drinks
  {
    id: 'drink-1',
    category: 'Drinks',
    name: 'Masala Chai',
    description: 'Brewed Assam tea, crushed ginger, cardamom, clove, whole milk',
    price: '₹180',
    veg: true,
    chefsPick: false,
    note: 'A warm welcome, any time of day.',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
    ingredients: ['Assam Black Tea', 'Fresh Ginger', 'Cardamom Pods', 'Whole Clove', 'Whole Milk'],
    allergens: 'Dairy',
    pairing: 'Papdi Chaat or Gajar Halwa',
  },
  {
    id: 'drink-2',
    category: 'Drinks',
    name: 'Nimbu Pani',
    description: 'Freshly squeezed lime, roasted cumin, mint leaves, rock salt',
    price: '₹160',
    veg: true,
    chefsPick: false,
    note: 'Bright, salty, and endlessly refreshing.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
    ingredients: ['Fresh Lime Juice', 'Roasted Cumin', 'Mint Leaves', 'Kala Namak', 'Sparkling Water'],
    allergens: 'None',
    pairing: 'Amritsari Fish Tikka',
  },
  {
    id: 'drink-3',
    category: 'Drinks',
    name: 'Smoked Tamarind Old Fashioned',
    description: 'Bourbon whiskey, tamarind reduction, jaggery syrup, smoked wood bitters',
    price: '₹525',
    veg: true,
    chefsPick: true,
    note: 'A slow sipper with a smoky black-tea finish.',
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=600&q=80',
    ingredients: ['Bourbon Whiskey', 'Tamarind Reduction', 'Raw Jaggery', 'Angostura Bitters', 'Orange Peel'],
    allergens: 'None',
    pairing: 'Seekh Kebab or Rogan Josh',
  },
  {
    id: 'drink-4',
    category: 'Drinks',
    name: 'Jeera Soda',
    description: 'Hand-ground roasted cumin, lime juice, club soda, black salt',
    price: '₹195',
    veg: true,
    chefsPick: false,
    note: 'The cure for a hot Delhi afternoon.',
    image: 'https://images.unsplash.com/photo-1621263764928-df1444c5e859?auto=format&fit=crop&w=600&q=80',
    ingredients: ['Roasted Cumin', 'Lime Juice', 'Black Salt', 'Club Soda', 'Fresh Mint'],
    allergens: 'None',
    pairing: 'Butter Chicken',
  },
  {
    id: 'drink-5',
    category: 'Drinks',
    name: 'Saffron Mango Lassi',
    description: 'Cultured yogurt, Alphonso mango pulp, Kashmiri saffron threads, cardamom',
    price: '₹250',
    veg: true,
    chefsPick: true,
    note: 'Velvety sweet with a fragrant saffron aroma.',
    image: 'https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=600&q=80',
    ingredients: ['Hung Curd', 'Alphonso Mango', 'Kashmiri Saffron', 'Green Cardamom', 'Pistachio Flakes'],
    allergens: 'Dairy, Tree Nuts',
    pairing: 'Tandoori Chicken',
  },

  // Desserts
  {
    id: 'dessert-1',
    category: 'Desserts',
    name: 'Gulab Jamun',
    description: 'Warm milk solid dumplings, saffron rabri, pistachio dust, edible rose',
    price: '₹295',
    veg: true,
    chefsPick: false,
    note: 'Warm, syrupy, and best shared.',
    image: 'https://images.unsplash.com/photo-1605197586548-0248a37943c2?auto=format&fit=crop&w=600&q=80',
    ingredients: ['Khoya', 'Saffron Rabri', 'Sugar Syrup', 'Pistachio Flakes', 'Rose Water'],
    allergens: 'Dairy, Gluten, Tree Nuts',
    pairing: 'Masala Chai',
  },
  {
    id: 'dessert-2',
    category: 'Desserts',
    name: 'Gajar Halwa',
    description: 'Red Delhi carrots slow-cooked in ghee, khoya, crushed cardamom',
    price: '₹275',
    veg: true,
    chefsPick: false,
    note: 'Slow-cooked until the carrots turn jewel-bright.',
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=600&q=80',
    ingredients: ['Delhi Red Carrots', 'Desi Ghee', 'Khoya', 'Green Cardamom', 'Cashew Nuts'],
    allergens: 'Dairy, Tree Nuts',
    pairing: 'Masala Chai',
  },
  {
    id: 'dessert-3',
    category: 'Desserts',
    name: 'Kulfi Falooda',
    description: 'Pistachio clay-pot kulfi, basil seeds, rose vermicelli, rabri drip',
    price: '₹325',
    veg: true,
    chefsPick: true,
    note: 'Cool, floral, and unapologetically festive.',
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=600&q=80',
    ingredients: ['Pistachio Kulfi', 'Sabja (Basil) Seeds', 'Rose Vermicelli', 'Condensed Milk'],
    allergens: 'Dairy, Tree Nuts',
    pairing: 'Post-dinner digestive',
  },
  {
    id: 'dessert-4',
    category: 'Desserts',
    name: 'Smoked Chocolate Torte',
    description: 'Dark cocoa torte infused with hickory woodsmoke, jaggery caramel, sea salt',
    price: '₹350',
    veg: true,
    chefsPick: true,
    note: 'Decadent dark chocolate kissed by oak timber smoke.',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80',
    ingredients: ['70% Dark Chocolate', 'Hickory Smoke Infusion', 'Jaggery Caramel', 'Flaky Sea Salt'],
    allergens: 'Dairy, Soy',
    pairing: 'Smoked Tamarind Old Fashioned',
  },
  {
    id: 'dessert-5',
    category: 'Desserts',
    name: 'Rasmalai Tres Leches',
    description: 'Soft cottage cheese discs soaked in cardamom milk cake, saffron cream',
    price: '₹340',
    veg: true,
    chefsPick: false,
    note: 'A modern blend of classic rasmalai and milk sponge.',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80',
    ingredients: ['Chhena Discs', 'Cardamom Milk', 'Saffron Cream', 'Almond Slivers'],
    allergens: 'Dairy, Gluten, Tree Nuts',
    pairing: 'Masala Chai',
  },
]
